import type { BudgetSource } from "./budget-source";

const LICENSE_UNCONFIRMED = "確認中";

export const BUDGET_SOURCES = [
  {
    id: "enacted",
    sourceUrl:
      "https://www.zaimu.metro.tokyo.lg.jp/zaisei/yosan/r8/8yosangaiyounituite",
    sourceTitle: "令和8年度予算概要",
    sourceDate: "2026-04-24",
    fiscalYear: 2026,
    documentStage: "enacted_budget",
    retrievedAt: "2026-08-06T21:50:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年度予算概要",
    targetTableOrItem: "一般会計の規模、目的別歳出、都税、基金および都債",
    appUsage: ["シミュレーターの基準額", "予算成立過程の成立予算", "財政条件の詳細"],
  },
  {
    id: "csv",
    sourceUrl:
      "https://catalog.data.metro.tokyo.lg.jp/dataset/t000004d0000000005",
    sourceTitle: "TOKYO予算見える化ボード データ一覧",
    sourceDate: "2026-01-30",
    fiscalYear: 2026,
    documentStage: "enacted_budget",
    retrievedAt: "2026-08-06T21:48:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "open_data_catalog",
    license: "クリエイティブ・コモンズ 表示（CC BY 4.0）",
    targetPage: "TOKYO予算見える化ボード データ一覧",
    targetTableOrItem: "一般歳出の目的別内訳を含む令和8年度CSV一覧",
    appUsage: ["9分野の成立予算額の照合"],
  },
  {
    id: "proposal",
    sourceUrl:
      "https://www.zaimu.metro.tokyo.lg.jp/zaisei/yosan/r8/8nendo_tokyotoyosan_an_gaiyou",
    sourceTitle: "令和8年度東京都予算案の概要",
    sourceDate: "2026-01-30",
    fiscalYear: 2026,
    documentStage: "proposal",
    retrievedAt: "2026-08-06T21:51:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年度東京都予算案の概要",
    targetTableOrItem: "一般会計予算案および主要施策",
    appUsage: ["予算成立過程の予算案"],
  },
  {
    id: "request",
    sourceUrl:
      "https://www.zaimu.metro.tokyo.lg.jp/zaisei/yosan/r8/08yosanyokyujokyou_index/",
    sourceTitle: "令和8年度予算要求",
    sourceDate: "2025-11",
    fiscalYear: 2026,
    documentStage: "request",
    retrievedAt: "2026-08-06T21:52:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年度予算要求",
    targetTableOrItem: "各局予算要求概要および要求額",
    appUsage: ["分野別の要求背景", "予算成立過程の各局要求"],
  },
  {
    id: "bureau",
    sourceUrl:
      "https://www.zaimu.metro.tokyo.lg.jp/zaisei/yosan/r8/8zaimukyokusateikekka",
    sourceTitle: "令和8年度一般会計予算 財務局査定結果（事項別）",
    sourceDate: "2026-01",
    fiscalYear: 2026,
    documentStage: "bureau_assessment",
    retrievedAt: "2026-08-06T21:53:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年度一般会計予算 財務局査定結果（事項別）",
    targetTableOrItem: "要求額から1億円以上増減した事項",
    appUsage: ["分野別の財務局査定例", "予算成立過程の財務局査定"],
  },
  {
    id: "governor",
    sourceUrl:
      "https://www.zaimu.metro.tokyo.lg.jp/zaisei/yosan/r8/8chijisateikekka",
    sourceTitle: "令和8年度一般会計予算 知事査定結果",
    sourceDate: "2026-01-30",
    fiscalYear: 2026,
    documentStage: "governor_assessment",
    retrievedAt: "2026-08-06T21:53:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年度一般会計予算 知事査定結果",
    targetTableOrItem: "知事査定で変更された事項",
    appUsage: ["分野別の知事査定例", "予算成立過程の知事査定"],
  },
  {
    id: "parties",
    sourceUrl:
      "https://www.zaimu.metro.tokyo.lg.jp/zaisei/yosan/r8/08seitoyobo",
    sourceTitle: "令和8年度都議会各会派からの要望",
    sourceDate: "2025-12",
    fiscalYear: 2026,
    documentStage: "external_request",
    retrievedAt: "2026-08-06T21:51:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年度都議会各会派からの要望",
    targetTableOrItem: "会派別の予算要望資料",
    appUsage: ["予算成立過程の外部要望"],
  },
  {
    id: "groups",
    sourceUrl:
      "https://www.zaimu.metro.tokyo.lg.jp/zaisei/yosan/r8/08dantaiyobo_index",
    sourceTitle: "各種団体からの東京都予算に対するヒアリング",
    sourceDate: "2025-11",
    fiscalYear: 2026,
    documentStage: "external_request",
    retrievedAt: "2026-08-06T21:51:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "各種団体からの東京都予算に対するヒアリング",
    targetTableOrItem: "団体別ヒアリング資料",
    appUsage: ["予算成立過程の外部要望"],
  },
  {
    id: "evaluation",
    sourceUrl:
      "https://catalog.data.metro.tokyo.lg.jp/dataset/t000004d2000000024",
    sourceTitle:
      "TOKYO政策評価・事業評価・グループ連携事業評価見える化ボード",
    sourceDate: "2026",
    fiscalYear: 2026,
    documentStage: "evaluation",
    retrievedAt: "2026-08-06T21:49:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "open_data_catalog",
    license: LICENSE_UNCONFIRMED,
    targetPage: "政策・事業評価見える化ボード",
    targetTableOrItem: "政策評価・事業評価の公開データ",
    appUsage: ["予算成立過程の政策・事業評価"],
  },
  {
    id: "assembly-review",
    sourceUrl: "https://www.gikai.metro.tokyo.lg.jp/record/budget/2026/",
    sourceTitle: "令和8年 予算特別委員会速記録",
    sourceDate: "2026-03",
    fiscalYear: 2026,
    documentStage: "assembly_review",
    retrievedAt: "2026-08-09T15:00:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_legislature",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年 予算特別委員会速記録",
    targetTableOrItem: "令和8年度予算の審査日程および速記録",
    appUsage: ["予算成立過程の都議会審議"],
  },
  {
    id: "assembly-vote",
    sourceUrl: "https://www.gikai.metro.tokyo.lg.jp/bill/reg2026-1.html",
    sourceTitle: "令和8年第1回定例会 提出議案と議決結果",
    sourceDate: "2026-03-27",
    fiscalYear: 2026,
    documentStage: "enacted_budget",
    retrievedAt: "2026-08-09T15:00:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_legislature",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年第1回定例会 提出議案と議決結果",
    targetTableOrItem: "令和8年度東京都一般会計予算の議決結果",
    appUsage: ["予算成立過程の議決・成立"],
  },
  {
    id: "execution-instruction",
    sourceUrl:
      "https://www.zaimu.metro.tokyo.lg.jp/information/press/r7/imeitsutatsu",
    sourceTitle: "令和8年度予算の執行について（依命通達）",
    sourceDate: "2026-03-31",
    fiscalYear: 2026,
    documentStage: "execution",
    retrievedAt: "2026-08-09T15:00:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "令和8年度予算の執行について（依命通達）",
    targetTableOrItem: "令和8年度予算の執行方針",
    appUsage: ["予算成立過程の事業執行"],
  },
  {
    id: "settlement-portal",
    sourceUrl: "https://www.zaimu.metro.tokyo.lg.jp/zaisei/kessan",
    sourceTitle: "東京都財務局 決算",
    sourceDate: "2026",
    fiscalYear: 2026,
    documentStage: "settlement",
    retrievedAt: "2026-08-09T15:00:00+09:00",
    factOrInterpretation: "fact",
    sourceType: "local_government",
    license: LICENSE_UNCONFIRMED,
    targetPage: "東京都財務局 決算",
    targetTableOrItem: "年度別決算資料の公開状況",
    appUsage: ["予算成立過程の決算と未確定表示"],
  },
] as const satisfies readonly BudgetSource[];
