/* Generated from docs/tokyo_budget_participation_research_prompt_v2.md. */
import type { OfficialContact } from "./participation-topic";

export const OFFICIAL_CONTACTS = {
  "tokyo-resident-voice-guide": {
    "contactId": "tokyo-resident-voice-guide",
    "contactOrganizationId": "tokyo-metropolitan-government",
    "contactOrganizationName": "東京都（都民の声総合窓口）",
    "contactLabel": "都民の声総合窓口（留意事項・各局案内）",
    "contactKind": "general_contact",
    "contactUrl": "https://www.metro.tokyo.lg.jp/tosei/iken-sodan/tominnokoe/ryuijikou",
    "contactSourceUrl": "https://www.metro.tokyo.lg.jp/tosei/iken-sodan/tominnokoe/ryuijikou",
    "contactPurpose": "福祉局の直接窓口本文を今回確認できなかったため、安全な共通フォールバックとして案内。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "health-medical-resident-voice-form": {
    "contactId": "health-medical-resident-voice-form",
    "contactOrganizationId": "health-medical-bureau",
    "contactOrganizationName": "東京都保健医療局",
    "contactLabel": "東京の保健医療についてあなたの声をお寄せください",
    "contactKind": "opinion_form",
    "contactUrl": "https://logoform.jp/form/tmgform/297877",
    "contactSourceUrl": "https://www.hokeniryo.metro.tokyo.lg.jp/contact",
    "contactPurpose": "保健医療局の事業に関する要望・意見を直接送るフォーム。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "health-medical-contact-directory": {
    "contactId": "health-medical-contact-directory",
    "contactOrganizationId": "health-medical-bureau",
    "contactOrganizationName": "東京都保健医療局",
    "contactLabel": "お問い合わせ",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.hokeniryo.metro.tokyo.lg.jp/contact",
    "contactSourceUrl": "https://www.hokeniryo.metro.tokyo.lg.jp/contact",
    "contactPurpose": "保健医療局の分野・内容別の問い合わせ先と、都民の声窓口を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "education-org-directory": {
    "contactId": "education-org-directory",
    "contactOrganizationId": "education-bureau",
    "contactOrganizationName": "東京都教育委員会（教育庁）",
    "contactLabel": "教育庁組織アドレス",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/031_kyoiku/kyoiku-address.htm",
    "contactSourceUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/031_kyoiku/kyoiku-address.htm",
    "contactPurpose": "教育庁の組織・担当部署・電話番号を確認できる一覧。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "education-inquiry-guide": {
    "contactId": "education-inquiry-guide",
    "contactOrganizationId": "education-bureau",
    "contactOrganizationName": "東京都教育委員会（教育庁）",
    "contactLabel": "教育委員会お問い合わせ",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.kyoiku.metro.tokyo.lg.jp/inquiry",
    "contactSourceUrl": "https://www.kyoiku.metro.tokyo.lg.jp/inquiry",
    "contactPurpose": "所管外・担当別の問い合わせ先を確認する案内。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "life-culture-org-directory": {
    "contactId": "life-culture-org-directory",
    "contactOrganizationId": "life-culture-bureau",
    "contactOrganizationName": "東京都生活文化局",
    "contactLabel": "生活文化局組織アドレス",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/047_seikatubunka/seikatubunka-address.htm",
    "contactSourceUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/047_seikatubunka/seikatubunka-address.htm",
    "contactPurpose": "生活文化局・私学部の担当部署と連絡先を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "sports-resident-voice": {
    "contactId": "sports-resident-voice",
    "contactOrganizationId": "sports-promotion-hq",
    "contactOrganizationName": "東京都スポーツ推進本部",
    "contactLabel": "都民の声",
    "contactKind": "general_contact",
    "contactUrl": "https://www.sports-tokyo-info.metro.tokyo.lg.jp/seisaku/about/tominnokoe.html",
    "contactSourceUrl": "https://www.sports-tokyo-info.metro.tokyo.lg.jp/seisaku/about/tominnokoe.html",
    "contactPurpose": "スポーツ推進本部の事業への意見、提言、要望、苦情、相談、問合せをEメール・手紙・電話・FAXで受け付ける案内。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "industry-org-directory": {
    "contactId": "industry-org-directory",
    "contactOrganizationId": "industry-labor-bureau",
    "contactOrganizationName": "東京都産業労働局",
    "contactLabel": "産業労働局組織アドレス",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/029_sangyo-rodo/sangyo-rodo-address.htm",
    "contactSourceUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/029_sangyo-rodo/sangyo-rodo-address.htm",
    "contactPurpose": "産業労働局のテーマ別担当部署と電話番号を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "startup-strategy-reference": {
    "contactId": "startup-strategy-reference",
    "contactOrganizationId": "startup-strategy-hq",
    "contactOrganizationName": "東京都スタートアップ戦略推進本部",
    "contactLabel": "スタートアップ戦略の推進",
    "contactKind": "reference",
    "contactUrl": "https://www.startupandglobalfinancialcity.metro.tokyo.lg.jp/startup",
    "contactSourceUrl": "https://www.startupandglobalfinancialcity.metro.tokyo.lg.jp/startup",
    "contactPurpose": "スタートアップ戦略・支援内容を確認する参考ページ。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "environment-org-directory": {
    "contactId": "environment-org-directory",
    "contactOrganizationId": "environment-bureau",
    "contactOrganizationName": "東京都環境局",
    "contactLabel": "組織と業務案内",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.kankyo.metro.tokyo.lg.jp/about/organization/",
    "contactSourceUrl": "https://www.kankyo.metro.tokyo.lg.jp/about/organization/",
    "contactPurpose": "環境局の担当部署、所管事務と提言・要望等への導線をテーマ別に確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "tokyo-org-reference": {
    "contactId": "tokyo-org-reference",
    "contactOrganizationId": "tokyo-metropolitan-government",
    "contactOrganizationName": "東京都",
    "contactLabel": "東京都の組織・各局のページ",
    "contactKind": "reference",
    "contactUrl": "https://www.metro.tokyo.lg.jp/about/soshiki",
    "contactSourceUrl": "https://www.metro.tokyo.lg.jp/about/soshiki",
    "contactPurpose": "水道局という別所管が存在することを確認する参考資料。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "urban-resident-voice": {
    "contactId": "urban-resident-voice",
    "contactOrganizationId": "urban-development-bureau",
    "contactOrganizationName": "東京都都市整備局",
    "contactLabel": "都市整備局都民の声窓口",
    "contactKind": "general_contact",
    "contactUrl": "https://www.toshiseibi.metro.tokyo.lg.jp/about/jouhou/madoguchi",
    "contactSourceUrl": "https://www.toshiseibi.metro.tokyo.lg.jp/about/jouhou/madoguchi",
    "contactPurpose": "都市整備局事業への都民の声の受付部署・連絡先と入力フォームへの案内を掲載。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "housing-org-directory": {
    "contactId": "housing-org-directory",
    "contactOrganizationId": "housing-policy-hq",
    "contactOrganizationName": "東京都住宅政策本部",
    "contactLabel": "住宅政策本部組織アドレス",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/109_juutakuseisaku/juutakuseisaku-address.htm",
    "contactSourceUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/109_juutakuseisaku/juutakuseisaku-address.htm",
    "contactPurpose": "住宅政策本部の担当部署・電話番号を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "construction-inquiry": {
    "contactId": "construction-inquiry",
    "contactOrganizationId": "construction-bureau",
    "contactOrganizationName": "東京都建設局",
    "contactLabel": "お問い合わせ",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.kensetsu.metro.tokyo.lg.jp/inquiry",
    "contactSourceUrl": "https://www.kensetsu.metro.tokyo.lg.jp/inquiry",
    "contactPurpose": "道路・河川・公園等の問い合わせ先、都民の声や専用相談への導線を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "mpd-opinion": {
    "contactId": "mpd-opinion",
    "contactOrganizationId": "metropolitan-police",
    "contactOrganizationName": "警視庁",
    "contactLabel": "警視庁の業務に対する苦情・ご要望・ご意見",
    "contactKind": "opinion_form",
    "contactUrl": "https://www.keishicho.metro.tokyo.lg.jp/anket/opinion.html",
    "contactSourceUrl": "https://www.keishicho.metro.tokyo.lg.jp/anket/opinion.html",
    "contactPurpose": "警視庁の業務への苦情、要望、意見を入力できるフォーム。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "tfd-opinion-form": {
    "contactId": "tfd-opinion-form",
    "contactOrganizationId": "tokyo-fire-department",
    "contactOrganizationName": "東京消防庁",
    "contactLabel": "お問い合わせフォーム",
    "contactKind": "opinion_form",
    "contactUrl": "https://www.tfd.metro.tokyo.lg.jp/form/index.php?f=tomin_form_01.html",
    "contactSourceUrl": "https://www.tfd.metro.tokyo.lg.jp/form/index.php?f=tomin_form_01.html",
    "contactPurpose": "相談・問合せ・要望・意見・苦情・情報等を送信できる東京消防庁のフォーム。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "tokyo-disaster-directory": {
    "contactId": "tokyo-disaster-directory",
    "contactOrganizationId": "tokyo-metropolitan-government",
    "contactOrganizationName": "東京都（防災ホームページ）",
    "contactLabel": "お問い合わせ窓口",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.bousai.metro.tokyo.lg.jp/link/1000044/1000252.html",
    "contactSourceUrl": "https://www.bousai.metro.tokyo.lg.jp/link/1000044/1000252.html",
    "contactPurpose": "防災分野を内容別に、総務局・建設局・保健医療局・水道局・下水道局・警視庁・東京消防庁等へ案内する。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "policy-org-directory": {
    "contactId": "policy-org-directory",
    "contactOrganizationId": "policy-planning-bureau",
    "contactOrganizationName": "東京都政策企画局",
    "contactLabel": "政策企画局組織アドレス",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/001_seisakukikaku/seisakukikaku-address.htm",
    "contactSourceUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/001_seisakukikaku/seisakukikaku-address.htm",
    "contactPurpose": "政策企画局の担当部署と連絡先を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "general-affairs-org-directory": {
    "contactId": "general-affairs-org-directory",
    "contactOrganizationId": "general-affairs-bureau",
    "contactOrganizationName": "東京都総務局",
    "contactLabel": "総務局組織アドレス",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/003_soumu/soumu-address.htm",
    "contactSourceUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/003_soumu/soumu-address.htm",
    "contactPurpose": "総務局の担当部署・連絡先を分野別に確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "election-business-directory": {
    "contactId": "election-business-directory",
    "contactOrganizationId": "election-commission",
    "contactOrganizationName": "東京都選挙管理委員会事務局",
    "contactLabel": "事業概要",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.senkyo.metro.tokyo.lg.jp/about/jigyougaiyou",
    "contactSourceUrl": "https://www.senkyo.metro.tokyo.lg.jp/about/jigyougaiyou",
    "contactPurpose": "総務課・選挙課等の担当業務と連絡先を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "finance-org-directory": {
    "contactId": "finance-org-directory",
    "contactOrganizationId": "finance-bureau",
    "contactOrganizationName": "東京都財務局",
    "contactLabel": "財務局組織アドレス",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/006_zaimu/zaimu-address.htm",
    "contactSourceUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/006_zaimu/zaimu-address.htm",
    "contactPurpose": "財政課・公債課等の担当部署と連絡先を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  },
  "tax-org-directory": {
    "contactId": "tax-org-directory",
    "contactOrganizationId": "tax-bureau",
    "contactOrganizationName": "東京都主税局",
    "contactLabel": "主税局組織アドレス",
    "contactKind": "inquiry_directory",
    "contactUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/008_tax/tax-address.htm",
    "contactSourceUrl": "https://www.soshiki-address.metro.tokyo.lg.jp/008_tax/tax-address.htm",
    "contactPurpose": "主税局の税目・担当部署・連絡先を確認できる。",
    "verifiedAt": "2026-08-11",
    "verificationStatus": "verified"
  }
} as const satisfies Record<string, OfficialContact>;
